### ISSUE TITLE
Add projects without affecting existing projects/programs in a well-defined structure.

### ISSUE THREAD

**Issue by hawk-lib** [hawk-lib/hactoberfest2022#1]
Add your projects in a separate directory/folder.

**Comment by DelayCoderz** [comment]
> Add your Android project here.

@hawk-lib can you assign me to this issue ?

**Comment by hawk-lib** [comment]
Yes, you can.

**Comment by Manav0702** [comment]
@hawk-lib can you assign  this issue to me ?

**Comment by hawk-lib** [comment]
@Manav0702 yes
