### ISSUE TITLE
Manage this Repository in a well-defined structure.

### ISSUE THREAD

**Issue by hawk-lib** [hawk-lib/hactoberfest2022#45]
Sort programs according to category and store them in a named directory.

**Comment by coolestnick** [comment]
Sir Please assign me this task, I will make sure to manage the repository well!

**Comment by Rohans-7** [comment]
Hey @hawk-lib please assign this to me. I will do this in a well stuructured manner and this will be a good contribution from me.
Thank you !!!!

**Comment by hawk-lib** [comment]
This Repo has been excluded from from hactoberfest. Follow this one - https://github.com/BuddyCode/hactoberfest2022
